name: CI
on: [push, pull_request, workflow_dispatch]

jobs: # {{{
  build-and-quicktest: # {{{

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04   # oldest available
          - ubuntu-latest
          - macos-11       # oldest available
          - macos-latest
          - windows-2019   # oldest available
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build nosh
        run: go build

      - name: Run a quicktest
        run: ./nosh quicktest.nosh
  # }}}
# }}}
