name: CI

on:
  push:
    branches: [ main, gh-actions ]
  pull_request:
    branches: [ main, gh-actions ]

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs: # {{{
  build-and-quicktest: # {{{

    strategy:
      matrix:
        os:
          - ubuntu-18.04   # oldest available
          - ubuntu-latest
          - macos-10.15    # oldest available
          - macos-latest
          - windows-2019   # oldest available
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build nosh
        run: go build

      - name: Run a quicktest
        run: ./nosh quicktest.star
  # }}}
# }}}
