name: CI

on:
  push:
    branches: [ main, gh-actions ]
  pull_request:
    branches: [ main, gh-actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: # {{{
  build-and-quicktest: # {{{

    strategy:
      matrix:
        os:
          - { id: ubuntu-latest , bin_ext: "" }
          - { id: macos-latest  , bin_ext: "" }
          - { id: macos-latest  , bin_ext: ".exe" }

    runs-on: ${{ matrix.os.id }}

    steps:
      - uses: actions/checkout@v3

      - name: Build nosh
        run: go build

      - name: Run a quicktest
        run: ./nosh${{ matrix.os.bin_ext }} quicktest.star
  # }}}
# }}}
