name: CI

on:
  push:
    branches: [ main, gh-actions ]
  pull_request:
    branches: [ main, gh-actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:

    strategy:
      matrix:
        os:
          - { name: ubuntu-latest }
          - { name: macos-latest }
          - { name: windows-latest }

    steps:
      - uses: actions/checkout@v3

      - name: Build nosh
        run: go build

      - name: Run a quicktest
        run: ./nosh quicktest.star

